### PR TITLE
Yaml changes stabikat 2024 08

### PR DESCRIPTION
**Pull request by annekauf**
Productive Updates added to our current status of yaml on main.

### CODE REVIEW

**Comment by annekauf** [comment]
grafik

nested.cy.js has 2 tests less than in prior PR (can't remember why)
1 more failed test than in prior PR in "chronology"

**Comment by annekauf** [comment]
Removing productive updates BKL browse in yaml has no impact on #58 but solved one failing test in topical.cy.js. (and no other failing test)
BUT: is part of productive Stabikat, so probably can't be removed. Topical test has to be solved another way.
grafik

**Review by duncdrum — APPROVED** [review]
see #109 

let's continue like this

**Comment by annekauf** [comment]
grafik
test run from main 2024/12/04

**Pull request merged**
